# Generated by Django 3.2.3 on 2021-05-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postbacheca'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbacheca',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='postbacheca',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
